# Generated by Django 5.1.3 on 2024-11-24 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ride",
            fields=[
                ("id_ride", models.IntegerField(primary_key=True, serialize=False)),
                ("status", models.CharField(max_length=150)),
                ("pickup_latitude", models.FloatField()),
                ("pickup_longitude", models.FloatField()),
                ("dropoff_latitude", models.FloatField()),
                ("dropoff_longitude", models.FloatField()),
                ("pickup_time", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id_user", models.IntegerField(primary_key=True, serialize=False)),
                ("role", models.CharField(max_length=150)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="RideEvent",
            fields=[
                (
                    "id_ride_event",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("description", models.CharField(max_length=255)),
                ("created_at", models.DateField()),
                (
                    "ride",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ride_information.ride",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ride",
            name="id_driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ride_information.user"
            ),
        ),
    ]
