# Generated by Django 5.1.3 on 2024-11-24 23:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ride_information", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ride",
            name="status",
            field=models.CharField(
                choices=[
                    ("en-route", "En-Route"),
                    ("pickup", "Pickup"),
                    ("dropoff", "Dropoff"),
                ],
                default="en-route",
                max_length=150,
            ),
        ),
    ]
